### PR TITLE
fix: improve prompts for create and list applications

### LINKED ISSUE #27: List applications sometimes does not work
The `List Argo CD applications` prompt sometimes does not work. I've noticed that sometimes AI executes `{"search": "*"}` request which won't return apps. Argo CD does not support glob expressions - it just looks for apps with the `search` query value in a name.

I think we can improve parameter description to make sure modeal is not trying to use `*`.

### LINKED ISSUE #29: Model attempts to supply both name and server
When asked to create an application which targets cluster by name instead of server the model supplies both name and server. I believe it is because server is not optional in the schema:

Note: The namespace field is optional as well.

https://github.com/akuity/argocd-mcp/blob/c1e8f69cabca82b615ce5f9150ff7d5f0a2b8bb7/src/shared/models/schema.ts#L48-L52

### PR DESCRIPTION
**Pull request by jiachengxu**
Fixes #27 by explicitly mentioning the `search` parameter doesn't support glob expression in the prompt
Fixes #29 by making server and name optional and adding validation in zod

### CODE REVIEW

File: src/shared/models/schema.ts [hunk 1]
```diff
@@ -46,9 +46,21 @@ export const ApplicationSchema = z.object({
...
     destination: z.object({
-      server: z.string(),
-      namespace: z.string(),
+      server: z.string().optional(),
+      namespace: z.string().optional(),
       name: z.string().optional()
     })
+      .refine(
+        data =>
+          (data.server === undefined && data.name !== undefined) ||
```
Comment (imwithye) [inline src/shared/models/schema.ts:55]: Will `(!data.server && !!data.name) || (!!data.server && !data.name)` be better in this case?

**Review by imwithye — APPROVED** [review]
